get:
  tags:
    - training
  summary: Get training job status
  operationId: getTrainingJob
  parameters:
    - $ref: ../components/parameters/JobId.yaml
  responses:
    '200':
      description: Job status and results
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TrainingJobStatus.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '500':
      $ref: ../components/responses/InternalError.yaml
